# Generated by Django 3.2.3 on 2021-05-17 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=30, validators=[main.models.only_letters_validator], verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, validators=[main.models.only_letters_validator], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, validators=[main.models.only_letters_validator], verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('birth_date', models.DateField(max_length=30, verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(validators=[main.models.only_letters_validator], verbose_name='врач-')),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'врачебные специльности',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.human')),
                ('qualification', models.TextField(blank=True, choices=[('первая', 'первая'), ('вторая', 'вторая'), ('высшая', 'высшая')], null=True, verbose_name='квалификация')),
                ('specialty', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='main.specialty', verbose_name='специальность')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
            bases=('main.human',),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_evenness', models.CharField(blank=True, choices=[('2', 'четный'), ('1', 'нечетный')], max_length=30, null=True, verbose_name='день')),
                ('start_time', models.TimeField(verbose_name='начало рабочего дня')),
                ('end_time', models.TimeField(verbose_name='конец рабочего дня')),
                ('doctor', models.OneToOneField(default='Null', on_delete=django.db.models.deletion.PROTECT, to='main.doctor', verbose_name='доктор')),
            ],
            options={
                'verbose_name': 'расписание врача',
                'verbose_name_plural': 'график врачей',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.human')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
            bases=('main.human',),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=None, verbose_name='день приема')),
                ('visit_time', models.TimeField(default=None, verbose_name='время примема')),
                ('status', models.TextField(blank=True, choices=[('прошел', 'прошел'), ('не прошел', 'не прошел')], default='не прошел', null=True, verbose_name='статус приема')),
                ('cost', models.CharField(blank=True, max_length=30, null=True, verbose_name='Стоимость(руб.)')),
                ('days_to_recover', models.IntegerField(blank=True, null=True, verbose_name='Дней для выздоровления')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Лечение')),
                ('doctor', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.PROTECT, to='main.doctor', verbose_name='доктор')),
                ('patient', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.PROTECT, to='main.patient', verbose_name='пациент')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'ordering': ['visit_date', 'visit_time'],
            },
        ),
    ]
