# Generated by Django 3.1.7 on 2021-03-17 13:24

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(validators=[main.models.only_letters_validator], verbose_name='Имя')),
                ('middle_name', models.TextField(validators=[main.models.only_letters_validator], verbose_name='Фамилия')),
                ('last_name', models.TextField(validators=[main.models.only_letters_validator], verbose_name='Отчество')),
                ('phone_number', models.TextField(default=False, verbose_name='Номер телефона')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, validators=[main.models.only_letters_validator], verbose_name='врач-')),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'врачебные специльности',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.human')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
            bases=('main.human',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.human')),
                ('qualification', models.TextField(blank=True, choices=[('первая', 'первая'), ('вторая', 'вторая'), ('высшая', 'высшая')], null=True)),
                ('specialty', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.PROTECT, to='main.specialty')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
            bases=('main.human',),
        ),
    ]
