# Generated by Django 3.1.7 on 2021-06-02 14:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='birth_date',
            field=models.DateField(max_length=30, validators=[main.models.birth_date_validator], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='human',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[main.models.phone_number_validator], verbose_name='Номер телефона'),
        ),
    ]
