# Generated by Django 3.1.7 on 2021-03-18 10:16

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.TextField(blank=True, choices=[('первая', 'первая'), ('вторая', 'вторая'), ('высшая', 'высшая')], null=True, verbose_name='квалификация'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(default='Null', on_delete=django.db.models.deletion.PROTECT, to='main.specialty', verbose_name='специальность'),
        ),
        migrations.AlterField(
            model_name='human',
            name='phone_number',
            field=models.TextField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.TextField(validators=[main.models.only_letters_validator], verbose_name='врач-'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(verbose_name='время приема')),
                ('status', models.TextField(blank=True, choices=[('прошел', 'прошел'), ('не прошел', 'не прошел')], null=True, verbose_name='статус приема')),
                ('cost', models.TextField(blank=True, null=True, verbose_name='Стоимость(руб.)')),
                ('days_to_recover', models.IntegerField(blank=True, null=True, verbose_name='Дней для выздоровления')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Лечение')),
                ('doctor', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.PROTECT, to='main.doctor', verbose_name='доктор')),
                ('patient', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.PROTECT, to='main.patient', verbose_name='пациент')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
