# Generated by Django 3.1.7 on 2021-03-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210318_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['visit_time'], 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_evenness', models.TextField(blank=True, choices=[('четный', 'четный'), ('не четный', 'не четный')], null=True, verbose_name='статус приема')),
                ('start_time', models.TimeField(verbose_name='начало рабочего дня')),
                ('end_time', models.TimeField(verbose_name='конец рабочего дня')),
                ('doctor', models.ForeignKey(default='Null', on_delete=django.db.models.deletion.PROTECT, to='main.doctor', verbose_name='доктор')),
            ],
        ),
    ]
