# Generated by Django 3.1.7 on 2021-03-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210318_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'расписание врача', 'verbose_name_plural': 'график врачей'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_evenness',
            field=models.TextField(blank=True, choices=[('четный', 'четный'), ('нечетный', 'нечетный')], null=True, verbose_name='день'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.OneToOneField(default='Null', on_delete=django.db.models.deletion.PROTECT, to='main.doctor', verbose_name='доктор'),
        ),
    ]
